spring:
  profiles:
    active: "local"
  datasource:
    platform: postgres
#    url: jdbc:postgresql://localhost:5432/goodreads?createDatabaseIfNotExist=true
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://localhost:5432/goodreads?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: true
    properties:
      hibernate.jdbc.batch_size: 100
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.generate_statistics: true
  flyway:
    enabled: false
  cache:
    jcache:
      config: classpath:ehcache.xml
server:
  address: 0.0.0.0
  port: 8080

management:
  server:
    port: 60001
  endpoints:
    web:
      path-mapping:
        health: "health"
        prometheus: "/metrics"
      base-path: "/"
      exposure:
        include:
          - health
          - prometheus
  health:
    mail:
      enabled: false

logging:
  level:
    org:
      hibernate:
        type: trace