spring:
  profiles:
    active: "local"
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/goodreads?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    tomcat.max-active: 15
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: true
  flyway:
    enabled: false
  cache:
    jcache:
      config: classpath:ehcache.xml
server:
  address: 0.0.0.0
  port: 8080

management:
  server:
    port: 60001
  endpoints:
    web:
      path-mapping:
        health: "health"
        prometheus: "/metrics"
      base-path: "/"
      exposure:
        include:
          - health
          - prometheus
  health:
    mail:
      enabled: false